#pragma once

#include "sampling/Sampler.h"

namespace tomcat {
    namespace model {

        /**
         * This class is responsible for estimating a DBN's parameters by
         * average over their samples generated by some sampler.
         */
        class DBNSamplingTrainer {
          public: // same pattern for protected and private in this order
            //------------------------------------------------------------------
            // Constructors & Destructor
            //------------------------------------------------------------------
            DBNSamplingTrainer(std::shared_ptr<Sampler> sampler);

            ~DBNSamplingTrainer();

            //------------------------------------------------------------------
            // Copy & Move constructors/assignments
            //------------------------------------------------------------------
            DBNSamplingTrainer(const DBNSamplingTrainer&) = default;

            DBNSamplingTrainer& operator=(const DBNSamplingTrainer&) = default;

            DBNSamplingTrainer(DBNSamplingTrainer&&) = default;

            DBNSamplingTrainer& operator=(DBNSamplingTrainer&&) = default;

            //------------------------------------------------------------------
            // Member functions
            //------------------------------------------------------------------
            void fit(std::shared_ptr<gsl_rng> random_generator, int num_samples);

            //------------------------------------------------------------------
            // Getters & Setters
            //------------------------------------------------------------------
            const std::shared_ptr<Sampler>& get_sampler() const;

          private:
            //------------------------------------------------------------------
            // Data members
            //------------------------------------------------------------------
            std::shared_ptr<Sampler> sampler;
        };

    } // namespace model
} // namespace tomcat
