#!/usr/bin/env python

# Script to combine annotations of incident commander inquiries from the Fall
# 2020 ASIST experiment.

import json
from pprint import pprint
import argparse
from glob import glob

parser = argparse.ArgumentParser()
parser.add_argument(
    "input_dir",
    help="Directory containing the annotation files (i.e. BORIS project files in JSON format)",
)

parser.add_argument(
    "output_file",
    help="Output file",
)

args = parser.parse_args()

for filepath in glob(f"{args.input_dir}/*")[0:1]:
    print("filepath: ", filepath)
    with open(filepath) as f:
        project = json.load(f)
        observations = project["observations"]
        for label, observation in observations.items():
            print(label)
            media_files = observation["file"]["1"]
            for k in observation["media_info"]["length"]:
                print("\t"+k)
            # for event in observation["events"]:
                # timestamp = event[0]
                # participant_id = event[1]
                # print(participant_id)
