#!/bin/bash

port=1883
network="host"
image="paho_mqtt_c_image"
container="paho_mqtt_c_container"

# build image
call="docker build . -t $image"
echo $call
$($call)

# run image
call="docker run --network=$network $image --name=$container"
echo $call
$($call)
