#!/bin/tcsh

echo "==================================================================================" >>& /home/svn/src/hooks/post-commit-src.log
echo "In script post-commit-src-2 at `date`" >>& /home/svn/src/hooks/post-commit-src.log
echo " " >>& /home/svn/src/hooks/post-commit-src.log

# setenv KJB_SRC_PATH "/home/ivilab/src/"
# setenv MAKE_PATH "${KJB_SRC_PATH}Make/"
# setenv BASE_PATH "/bin:/usr/bin:/home/ivilab/ivilab/scripts:${MAKE_PATH}scripts"
# source ${MAKE_PATH}init_compile >>& /home/svn/src/hooks/post-commit-src.log
echo "KJB_SRC_PATH is: ${KJB_SRC_PATH}" >>& /home/svn/src/hooks/post-commit-src.log
echo "MAKE_SCRIPT_PATH is: ${MAKE_SCRIPT_PATH}" >>& /home/svn/src/hooks/post-commit-src.log
echo "P_STDERR is ${P_STDERR}" >>& /home/svn/src/hooks/post-commit-src.log
echo " " >>& /home/svn/src/hooks/post-commit-src.log
rehash

set script_status = 0

# We introduce another level of entries so that high level output from internal and
# external post-commits can go to separate files, but detailed output goes to
# the same place. 
 
echo "Executing post-commit-src-3 with detailed output going to /home/svn/src/hooks/repo_sync.log."

post-commit-src-3 >>& /home/svn/src/hooks/repo_sync.log

if (${status}) then
    echo "Script post-commit-src-3 FAILED." >>& /home/svn/src/hooks/post-commit-src.log
    set script_status = 1 
else 
    echo "Script post-commit-src-3 SUCCEEDED." >>& /home/svn/src/hooks/post-commit-src.log
endif 

echo " " >>& /home/svn/src/hooks/post-commit-src.log
echo "Script post-commit-src-2 finishing at `date` with status ${script_status}" >>& /home/svn/src/hooks/post-commit-src.log
echo "This is the last output from this SVN initiated post-commit" >>& /home/svn/src/hooks/post-commit-src.log
echo " " >>& /home/svn/src/hooks/post-commit-src.log

exit script_status 

