#!/bin/tcsh 

# The master copy of this file lives in
#   svn+ssh://vision.cs.arizona.edu/home/svn/ivilab/scripts
# For it to do its job it needs to be copied to 
#   vision:/home/svn/ivilab/hooks/post-commit

setenv PATH "/bin:/usr/bin:/home/ivilab/ivilab/scripts"
rehash

set repo_path = "$1"
set exec_id = `whoami`

echo "-------------------------------------------------------" >> /home/svn/ivilab/hooks/post-commit.log
echo "repo_path: $repo_path" >> /home/svn/ivilab/hooks/post-commit.log
echo "exec_id: $exec_id" >> /home/svn/ivilab/hooks/post-commit.log
echo "Executing post-commit-ivilab $1" >> /home/svn/ivilab/hooks/post-commit.log
echo " " >> /home/svn/ivilab/hooks/post-commit.log

# It is too dangerous to try to update scripts because we might be commiting "scripts"
# and then we would be fail because of a lockfile and have to run "svn cleanup"

# pushd /home/ivilab/ivilab/scripts > /dev/null
# if ($status) then
#     echo "Pushing to directory /home/ivilab/ivilab/scripts FAILED" |& tee -a /home/svn/ivilab/hooks/post-commit.log 
#     exit 1 
# endif  
# 
# svn up > /dev/null
# if ($status) then
#     echo "Update of `pwd` FAILED"  |& tee -a /home/svn/ivilab/hooks/post-commit.log 
#     exit 1 
# endif 

post-commit-ivilab "$1" 
if ($status) then
    echo "Execution of post-commit-ivilab $1 FAILED"  |& tee -a /home/svn/ivilab/hooks/post-commit.log 
    exit 1 
endif 

# popd > /dev/null

echo "-------------------------------------------------------" >> /home/svn/ivilab/hooks/post-commit.log

