#!/bin/csh

onintr cleanup
set noglob

if ($3 == "") then
    set parm = *
else 
    set parm = $3
endif 

unset noglob

set dir_1 = `echo $1/ | sed "s/\/\//\//g"`
set dir_2 = `echo $2/ | sed "s/\/\//\//g"`

set dir_1_pat = `echo $dir_1 | sed "s/\//\\\//g"`

set noglob

find $dir_1 -follow -name $parm | sed "s/$dir_1_pat//" | sed '/^ *$/d' | recursive_diff_helper $dir_1 $dir_2 

cleanup:
unset noglob


