#!/bin/tcsh 

##############################################################################
#
# Identification:
#     A script to 
#
# Description:
#     This script 
#
# Option arguments: 
#
# |    (The bar stops next line from joining) 
#         Indented
#
# Examples (more to come):
#     blah blah blah
#
# Bugs/deficiencies
#
# Author:
#     Kobus Barnard 
#
##############################################################################

@ num_args = ${#argv}

set label_to_skip = ""

# We accept one optional argument.
if (${num_args} == 1) then
    set label_to_skip = "$1"
else if (${num_args} > 1) then
    ${P_STDERR} "Script repo_sync_to_all_externals called with ${num_args} arguments."
    ${P_STDERR} "It needs either none or one."
    exit 1
endif 


if (! $?REPO_SYNC_RECURSION_PREFIX) then 
    ${P_STDERR} "REPO_SYNC_RECURSION_PREFIX was not set entering repo_sync_to_all_externals"
    setenv REPO_SYNC_RECURSION_PREFIX ""
    setenv IVI_OUTPUT_PREFIX "${REPO_SYNC_RECURSION_PREFIX}"
endif 

setenv KJB_VERBOSE 

set script_status =  0

if (${num_args} < 2) then
# We assume that we have /home/ivilab/ivilab/scripts in
# our path. We also assume that it was upated before we get here. 

cd /home/ivilab/repo_sync 

foreach external_dir (*_external)
    set external_label = `echo ${external_dir} | sed 's/_external$//'`
        
    ${VERBOSE_ECHO} "${REPO_SYNC_RECURSION_PREFIX}======================================================================================"
    ${VERBOSE_ECHO} " "

    if ("${external_label}" == "${label_to_skip}") then
        ${VERBOSE_ECHO} "${REPO_SYNC_RECURSION_PREFIX}Script repo_sync_to_all_externals skipping ${external_label}."
        continue
    else
        ${VERBOSE_ECHO} "${REPO_SYNC_RECURSION_PREFIX}Script repo_sync_to_all_externals processing ${external_label} at `date`"
    endif 

    ${VERBOSE_ECHO} " "
    endif 

    repo_sync_with_external "to" "${external_label}"
    set repo_sync_entity_status = ${status}

    if (${repo_sync_entity_status}) then 
        set script_status = 1
    endif 

    ${VERBOSE_ECHO} " "
    ${VERBOSE_ECHO} "${REPO_SYNC_RECURSION_PREFIX}Script repo_sync_to_all_externals DONE processing ${external_label} with status ${repo_sync_entity_status} at `date`"
    ${VERBOSE_ECHO} "${REPO_SYNC_RECURSION_PREFIX}Finished at `date` with status ${repo_sync_entity_status}"
    ${VERBOSE_ECHO} "${REPO_SYNC_RECURSION_PREFIX}@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
end

exit ${script_status}

