#!/bin/bash

set -u

# Install DLib from source

install_dlib_from_source() {
    local version=$1
    if ! pkg-config --atleast-version=${version} dlib-1; then
        if ! curl -L https://github.com/davisking/dlib/archive/v${version}.zip -o dlib.zip; then
            exit 1
        fi
        if ! unzip -qq dlib.zip; then exit 1; fi
        mv dlib-${version} dlib
        pushd dlib
            mkdir build
            pushd build
                cmake ..
                if ! cmake --build . --config Release; then
                    exit 1
                fi
                if [[ $OSTYPE == "linux-gnu" ]]; then
                    if ! make -j $(nproc); then exit 1; fi
                    if ! sudo make -j $(nproc) install; then exit 1; fi
                else
                    if ! make -j; then exit 1; fi
                    if ! sudo make -j install; then exit 1; fi
                fi
            popd
        popd
        /bin/rm -rf dlib*
    fi
}

install_dlib_from_source 19.20
exit 0
