#!/bin/bash

# Install DLib from source

install_dlib_from_source() {
    local version=$1
    if ! pkg-config --atleast-version=${version} dlib-1; then
        if ! curl -L https://github.com/davisking/dlib/archive/v${version}.zip -o dlib.zip; then
            exit 1
        fi
        if ! unzip -qq dlib.zip; then exit 1; fi
        mv dlib-${commit_sha} dlib
        pushd dlib
            mkdir build
            pushd build
                cmake ..
                if ! cmake --build . --config Release; then
                    exit 1
                fi
                if ! make -j8; then exit 1; fi
                if ! sudo make install; then exit 1; fi
            popd
        popd
        /bin/rm -rf dlib*
    fi
}

install_dlib_from_source 19.20
exit 0
