#!/bin/bash

# Install liblsl from source.

version=1.16.1
wget https://github.com/sccn/liblsl/archive/v$version.tar.gz
tar -xf v$version.tar.gz  
rm v$version.tar.gz

pushd liblsl-$version > /dev/null
  mkdir build
  cd build
  cmake ..
  sudo make -j install
popd > /dev/null

rm -rf liblsl-$version

exit 0
