#!/bin/bash

# Script to install MacPorts from source.
set -euo pipefail

install_macports() {

  # Version 2.7.0 is the latest as of May 21, 2021.
  local version=2.7.0

  curl -O https://distfiles.macports.org/MacPorts/MacPorts-$version.tar.bz2

  tar xf MacPorts-$version.tar.bz2

  pushd MacPorts-$version > /dev/null
    ./configure
    make -j
    make -j install
  popd > /dev/null

  # Remove the .tar.bz2 file
  /bin/rm -rf Macports-$version*
}

install_macports
exit 0
