# Rust as the base image
FROM rust:1.67

RUN USER=root cargo new --bin rust_agent
WORKDIR /rust_agent

RUN apt-get update
RUN apt-get install -y curl gcc make build-essential

COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

RUN cargo build --release
RUN rm src/*.rs

COPY ./src ./src

# Build for release.
RUN rm ./target/release/deps/rust_agent*
RUN cargo install --path .

CMD ["rust_agent"]
