# FROM ubuntu:20.04
# CMD bash

# RUN apt-get update
# RUN apt-get install -y curl gcc make build-essential 

#install Rust
# RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

#configure shell
# RUN . .cargo/env




# ENTRYPOINT cargo run



# 1. This tells docker to use the Rust official image
FROM rust:1.67

# 2. Copy the files in your machine to the Docker image
COPY ./ ./

# Build your program for release
RUN cargo build --release

# Run the binary
CMD ["./target/release/rust_agent"]
