#!/bin/bash

# Authors: Joseph Astier, Adarsh Pyarelal


mosquitto_sub \
-t "reference_agent_output_topic_1" \
-t "reference_agent_output_topic_2" \
-t "agent/control/rollcall/response" \
-t "status/reference_agent/heartbeats" \
-t "agent/reference_agent/versioninfo" | jq
