openapi: 3.0.0

info:
  title: ToMCAT Message Spec
  description: ToMCAT Message Spec
  version: "0.1"

paths:
  /observations/events/player_interactions/blocks/door:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorEvent'

  /observations/events/player_interactions/blocks/lever:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeverEvent'

  /observations/events/player_interactions/blocks/general:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockInteraction'

  /observations/events/player_interactions/left_clicks/blocks:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorEvent'

  /observations/events/player_interactions/break_events/blocks:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorEvent'

  /observations/events/entity_death:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorEvent'

  /observations/chat:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorEvent'

  /observations/events/dog_barks:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorEvent'


components:
  schemas:
    
          
    Position:
      description: "Position vector"
      properties:
        x:
          type: integer
        y:
          type: integer
        z:
          type: integer
          
    Velocity:
      description: "Velocity vector"
      properties:
        x:
          type: number
        y:
          type: number
        z:
          type: number

    Event:
      properties:
        header:
          $ref: '#/components/schemas/CommonHeader'
        msg:
          $ref: '#/components/schemas/Msg'
        event_type:
          type: string

    DoorEvent:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        data:
          $ref: '#/components/schemas/DoorEventData'

    LeverEvent:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        data:
          $ref: '#/components/schemas/LeverEventData'

    DoorEventData:
      properties:
        timestamp:
          type: string
          format: date-time
        player_name:
          type: string
          example: "Aptiminer1"
        was_open:
          type: boolean
        door_position:
          $ref: '#/components/schemas/Position'
      description: "Door event."

    LeverEventData:
      properties:
        timestamp:
          format: date-time
        player_name:
          type: string
          example: "tomcat"
        was_powered:
          type: boolean
        lever_position:
          $ref: '#/components/schemas/Position'
      description: "Lever event."

    BlockInteraction:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        player_name:
          type: string
        block_position:
          $ref: '#/components/schemas/Position'
        block_material:
          type: string
          example: minecraft:grass
        click_type:
          $ref: '#/components/schemas/ClickType'
        item_held:
          type: string

    EventType:
      type: string
      enum:
        - "Event:Lever"
        - "Event: Door"

    ClickType:
      type: string
      enum:
        - right
        - left
