openapi: 3.0.0

info:
  title: ToMCAT Message Spec
  description: ToMCAT Message Spec
  version: "0.1"

paths:
  /observations/state:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateObservation'

  /observations/events/player_interactions/blocks/door:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorInteraction'

  /observations/events/player_interactions/blocks/lever:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeverEvent'

  /observations/events/player_interactions/blocks/general:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericBlockInteraction'

  /observations/events/player_interactions/left_clicks/blocks:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorInteraction'

  /observations/events/player_interactions/break_events/blocks:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorInteraction'

  /observations/events/mob_attacked:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MobAttacked'

  /observations/events/entity_death:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityDeath'

  /observations/chat:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorInteraction'

  /observations/events/dog_barks:
    subscribe:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DogBarkEvent'


components:
  schemas:
    
    Position:
      description: "Position vector"
      properties:
        x:
          type: integer
          example: 10
        y:
          type: integer
          example: 20
        z:
          type: integer
          example: 30
          
    Velocity:
      description: "Velocity vector"
      properties:
        x:
          type: number
        y:
          type: number
        z:
          type: number

    Event:
      properties:
        timestamp:
          type: string
          format: date-time

    PlayerInteraction:
      allOf:
        - $ref: '#/components/schemas/Event'
      properties:
        player_name:
          $ref: '#/components/schemas/PlayerName'
        item_held:
          $ref: '#/components/schemas/Item'

    BlockInteraction:
      allOf:
      - $ref: '#/components/schemas/PlayerInteraction'
      properties:
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.BlockInteraction
        block_position:
          $ref: '#/components/schemas/Position'
        block_material:
          $ref: '#/components/schemas/BlockMaterial'
        click_type:
          $ref: '#/components/schemas/ClickType'

    DoorInteraction:
      allOf:
        - $ref: '#/components/schemas/BlockInteraction'
      properties:
        block_material:
          type: string
          examples:
            - minecraft:wooden_door
        block_type:
          type: string
          enum:
            - net.minecraft.block.BlockDoor
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.DoorInteraction
        was_open:
          type: boolean
      description: "Door event."

    LeverEvent:
      allOf:
      - $ref: '#/components/schemas/BlockInteraction'
      properties:
        block_material:
          type: string
          enum:
            - minecraft:lever
        block_type:
          type: string
          enum:
            - net.minecraft.block.BlockLever
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.LeverFlip
        was_powered:
          type: boolean
      description: "Lever event."


    GenericBlockInteraction:
      allOf:
      - $ref: '#/components/schemas/BlockInteraction'
      properties:
        block_material:
          type: string
          $ref: '#/components/schemas/BlockMaterial'
        block_type:
          $ref: '#/components/schemas/BlockType'
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.BlockInteraction
        was_powered:
          type: boolean
      description: "Generic block interaction event."

    MobAttacked:
      allOf:
      - $ref: '#/components/schemas/PlayerInteraction'
      properties:
        target_id:
          type: string
          format: uuid
        target_position:
          $ref: '#/components/schemas/Position'
        target_velocity:
          $ref: '#/components/schemas/Velocity'
        target_type:
          $ref: '#/components/schemas/EntityType'
        target_health:
          type: number
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.MobAttacked
      description: "Lever event."

    EntityDeath:
      allOf:
        - $ref: '#/components/schemas/Event'
      properties:
        entity_type:
          $ref: '#/components/schemas/EntityType'
        entity_name:
          type: string
          example: Zombie
        entity_id:
          type: string
          format: uuid
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.EntityDeath
      
    DogBarkEvent:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        number_of_barks:
          type: integer
          enum:
            - 1
            - 2
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.DogBarkEvent

    PlayerName:
      type: string
      example: tomcat

    BlockType:
      type: string
      example: net.minecraft.block.BlockAir

    StateObservation:
      properties:
        name:
          $ref: '#/components/schemas/PlayerName'
        header:
          properties:
            timestamp:
              type: string
              format: date-time
            message_type:
              type: string
              enum:
                - observation
            version:
              type: string
              example: "0.2"
        msg:
          properties:
            trial_id:
              type: string
              format: uuid
            timestamp:
              type: string
              format: date-time
            source:
              type: string
              example: human
            sub_type:
              type: string
              enum:
                - state
        data:
          properties:
            x:
              type: number
            y:
              type: number
            z:
              type: number
            motion_x:
              type: number
            motion_y:
              type: number
            motion_z:
              type: number
            pitch:
              type: number
            yaw:
              type: number
            world_time:
              type: integer
            total_time:
              type: integer
            id:
              type: string
              format: uuid
            name:
              $ref: '#/components/schemas/PlayerName'
            life:
              type: number
              example: 20.0



    BlockMaterial:
      type: string
      examples:
        - minecraft:air
        - minecraft:barrier
        - minecraft:clay
        - minecraft:glass
        - minecraft:gold_block
        - minecraft:grass
        - minecraft:stone_button
        - minecraft:wood

    Item:
      type: string
      example: Stone Axe

    EntityType:
      type: string
      examples:
        - net.minecraft.entity.monster.EntitySkeleton
        - net.minecraft.entity.monster.EntityZombie

    ClickType:
      type: string
      enum:
        - right
        - left
