#!/bin/bash 

##############################################################################
#
# Identification: 
#     Helper for cleanup_rsync_backups
#     
#
# Description:
#     
#
# Output:
#     
#
# Exit status:
#     Following unix convention, this script exits with 0 on success, and
#     non-zero if there was an error. 
#
# Author:
#     Kobus Barnard
#
##############################################################################

set -u

# Don't trap because diff fails if files differ. 
# source ${TOMCAT_DIR}shared_code/bash/ivi_error_trap.bash  

exit_status=0

# By assumption, $1 and thus file_name will have the string -RSYNC-
file_name=`echo ${1} | sed 's#^./##'`
# echo file_name: $file_name

base_name=`echo ${file_name} | sed 's#-RSYNC-.*##'`
# echo base_name: $base_name

if [[ -e "${base_name}"  ]]; then
    diff -q "${base_name}" "${file_name}" > /dev/null 
    diff_rc=$?
    if [[ ${diff_rc} -ne 0 ]]; then 
        ${VERBOSE_ECHO} "Keeping ${file_name} as it differs from ${base_name}"
    else 
        is_dir=`echo ${file_name} | grep -c '/'`

        if [[ "${is_dir}" -ne 0 ]]; then 
            dir_name=`echo ${file_name} | sed 's#^\(.*\)/.*$#\1#'`
            mkdir -p "${LIMBO_DIR}${dir_name}"
            exit_status=$?
            dir_name="${dir_name}/"
        else 
            dir_name=""
        fi 

        if [[ ${exit_status} -eq 0 ]]; then
            if [[ -e "${LIMBO_DIR}${dir_name}${file_name}" ]]; then
                ${VERBOSE_ECHO} "mv ${file_name} ${LIMBO_DIR}${dir_name}${file_name}-$$"
                mv "${file_name}" "${LIMBO_DIR}${dir_name}${file_name}-$$"
                exit_status=$?
            fi 
        fi 

        if [[ ${exit_status} -eq 0 ]]; then
            ${VERBOSE_ECHO} "mv ${file_name} ${LIMBO_DIR}${dir_name}"
            mv "${file_name}" "${LIMBO_DIR}${dir_name}"
        fi 
    fi 
else
    echo "WRN: Missing corresponding base file for ${1}"
fi 

exit ${exit_status}

