#!/bin/bash

set -u

USER=user
TIGER=192.168.0.xx
LION=192.168.0.xx
LEOPARD=192.168.0.xx

LAB_SCRIPTS_DIR="Documents/tomcat/tools/lab_scripts"

ssh $USER@${TIGER} "bash -s < ./${LAB_SCRIPTS_DIR}/pre_baseline"
ssh $USER@${LION} "bash -s < ./${LAB_SCRIPTS_DIR}/pre_baseline"
ssh $USER@${LEOPARD} "bash -s < ./${LAB_SCRIPTS_DIR}/pre_baseline"

exit 0
