(progn (ql:quickload "shop3")
       (load "util.lisp")
       (load "sar-individual-domain.lisp"))

(in-package :shop-user)
(defproblem sar-individual-problem ;; Example initial state and task
            ((building b)
             (goal sar-individual-example-goal.txt)
             (room lobby) 
             (room mens) 
             (room womens)
             (room e-1)
             (room e-2)
             (room main-Intersection)
             (room mid-left-bottom-hallway)
             (room far-left-bottom-hallway)
             (room lower-left-hallway)
             (room upper-left-hallway)
             (room r-j)
             (room r-201)
             (room r-208-a)
             (room r-203)
             (room r-208-b)
             (room r-205)
             (room r-210)
             (room r-207)
             (room lower-center-hallway)
             (room upper-center-hallway)
             (room mid-right-bottom-hallway)
             (room far-right-bottom-hallway)
             (room lower-right-hallway)
             (room upper-right-hallway)
             (room r-209)
             (room r-216-a)
             (room r-211)
             (room r-216-b)
             (room r-213)
             (room r-218)
             (room r-215)
             (room r-220)
             (rescuer t1))
            ((enter-building-and-complete-mission t1 b lobby)))

(find-plans 'sar-individual-problem :which :first :optimize-cost nil :verbose :plans :plan-tree nil)
