(progn (ql:quickload "shop3")
       (load "util.lisp")
       (load "sar-individual-domain.lisp"))

(in-package :shop-user)
(defproblem sar-individual-problem ;; Example initial state and task
            ((building b) 
             (room lobby) 
             (room mens) 
             (room womens)
             (room e-1)
             (room e-2)
             (room main-Intersection)
             (room mid-left-bottom-hallway)
             (room far-left-bottom-hallway)
             (room lower-left-hallway)
             (room upper-left-hallway)
             (room r-j)
             (room r-201)
             (room r-208-a)
             (room r-203)
             (room r-208-b)
             (room r-205)
             (room r-210)
             (room r-207)
             (room lower-center-hallway)
             (room upper-center-hallway)
             (room mid-right-bottom-hallway)
             (room far-right-bottom-hallway)
             (room lower-right-hallway)
             (room upper-right-hallway)
             (room r-209)
             (room r-216-a)
             (room r-211)
             (room r-216-b)
             (room r-213)
             (room r-218)
             (room r-215)
             (room r-220)
             (rescuer t1) 
             (victim v1) 
             (victim v2)          
             (victim v3) 
             (victim v4) 
             (victim v5) 
             (victim v6)
             (victim v7)
             (victim v8)
             (victim v9)
             (victim v10)
             (victim v11)
             (victim v12)
             (victim v13)
             (victim v14)
             (victim v15)
             (victim v16)
             (victim v17)
             (victim v18)
             (victim v19)
             (victim v20)
             (victim v21)
             (victim v22)
             (victim v23)
             (victim v24)
             (victim v25)
             (victim v26)
             (victim v27)
             (victim v28)
             (victim v29)
             (injured v1) 
             (injured v2) 
             (injured v3) 
             (injured v4) 
             (injured v5) 
             (injured v6)
             (injured v7)
             (injured v8)
             (injured v9)
             (injured v10)
             (injured v11)
             (injured v12)
             (injured v13)
             (injured v14)
             (injured v15)
             (injured v16)
             (injured v17)
             (injured v18)
             (injured v19)
             (injured v20)
             (injured v21)
             (injured v22)
             (injured v23)
             (injured v24)
             (injured v25)
             (injured v26)
             (injured v27)
             (injured v28)
             (injured v29)
             (in v1 womens) 
             (in v2 mens) 
             (in v3 mens) 
             (in v4 e-1) 
             (in v5 e-2)
             (in v6 upper-left-hallway)
             (in v7 r-j)
             (in v8 r-201)
             (in v9 r-201)
             (in v10 r-203)
             (in v11 r-205)
             (in v12 r-208-b)
             (in v13 r-207)
             (in v14 r-207)
             (in v15 r-207)
             (in v16 r-210)
             (in v17 r-210)
             (in v18 r-215)
             (in v19 r-215)
             (in v20 r-220)
             (in v21 r-220)
             (in v22 r-213)
             (in v23 r-213)
             (in v24 r-218)
             (in v25 r-218)
             (in v26 r-211)
             (in v27 r-216-b)
             (in v28 r-209)
             (in v29 r-216-a))
            ((enter-building-and-complete-mission t1 b lobby)))

(find-plans 'sar-individual-problem :which :first :optimize-cost nil :verbose :plans :plan-tree nil)
