#!/bin/bash

set -u

# Script to test if system audio recording is enabled.

blackhole_is_setup=$(ffmpeg -f avfoundation -list_devices true -i "" 2>&1 | grep "BlackHole 16ch")
multi_device_output_is_setup=$(ffmpeg -f avfoundation -list_devices true -i "" 2>&1 | grep "Multi-Device Output")
if [[ $blackhole_is_setup == "" || "$multi_device_output_is_setup" == "" ]]; then
  echo "BlackHole system audio recording virtual output device is not set up."
  echo "We will do it now."
  if ! "$TOMCAT"/tools/macos/activate_system_audio_recording; then exit 1; fi
fi

# Switching the audio output from the multi-output device to the built-in
# output.
if ! SwitchAudioSource -s "Multi-Output Device"; then exit 1; fi

exit 0
