#!/bin/bash

# Usage: ./autoformat_code

export TOMCAT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd)"

find "${TOMCAT}/external/malmo/Minecraft/src/main/java/" -name *.java | parallel --bar clang-format -i {}
