#!/bin/bash

set -u

export dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')

if [[ "$OSTYPE" == "darwin"* ]]; then
  export PATH="$PATH:/opt/local/bin:/opt/local/sbin"
  if [[ "$TERM_PROGRAM" == "iTerm.app" ]]; then
    export terminal="iTerm"
  else
    export terminal="Terminal"
  fi

  # On recent versions of macOS, we need to test whether the terminal has access
  # to the webcam and microphone.

  if (( "${ENABLE_FFMPEG:-1}" )); then
    export ffmpeg_fmt_webcam=avfoundation
    export ffmpeg_input_device_webcam="0:"

    macOS_minor_version=$(sw_vers -productVersion | cut -d '.' -f2)
    if (( $macOS_minor_version < 15 )); then
      echo "macOS version older than 10.15 (Catalina)."
      echo "System audio recording will be disabled."
      export ffmpeg_input_device_microphone=":0"
      export ENABLE_SYSTEM_AUDIO_RECORDING=0
    else
      # The default input microphone would normally be ":0", but since we
      # have installed BlackHole to record system audio, the input device
      # corresponding to the microphone is ":1".
      export ffmpeg_input_device_microphone=":1"
      export ffmpeg_input_device_system_audio=":0"
      export ffmpeg_fmt_system_audio=avfoundation
    fi

    export ffmpeg_fmt_microphone=avfoundation
    export ffmpeg_fmt_screen_capture=avfoundation
    export ffmpeg_input_device_screen_capture="1:"

    if [ ! "${GITHUB_ACTIONS:-false}" = "true" ]; then
      echo "Checking if webcam video recording works..."
      "${TOMCAT}"/tools/macos/test_webcam

      if (( "${ENABLE_SYSTEM_AUDIO_RECORDING:-1}" )); then
        echo "Checking if system audio recording is set up..."
        "${TOMCAT}"/tools/macos/test_system_audio_recording
      fi

      echo "Testing terminal access to microphone..."
      "${TOMCAT}"/tools/macos/test_microphone

      echo "Testing screen capture..."
      "${TOMCAT}"/tools/macos/test_screen_recording
    fi
  fi
  # Trying to set the correct version of Java.
  macports_found=`[ -x "$(command -v port)" ]; echo $?`
  if [[ $macports_found -eq 0 ]]; then
    export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home
  fi


elif [[ "$OSTYPE" == "linux-gnu" ]]; then
  if (( "${ENABLE_FFMPEG:-1}" )); then
    export ffmpeg_fmt_webcam=v4l2
    export ffmpeg_input_device_webcam=/dev/video0

    export ffmpeg_fmt_microphone=alsa
    export ffmpeg_input_device_microphone=default

    export ffmpeg_fmt_screen_capture=x11grab
    export ffmpeg_input_device_screen_capture=":0.0"
    export ENABLE_SYSTEM_AUDIO_RECORDING=0
  fi
else
  echo "OSTYPE is not darwin* or linux-gnu."
  echo "Most likely this operating system is not supported"
  exit 1
fi

if [ "${GITHUB_ACTIONS:-false}" = "true" ]; then
  export time_limit=1
  export do_tutorial_mission=0
  export mission=external/malmo/sample_missions/default_flat_1.xml
else
  export time_limit=600
fi

export do_main_mission=1
