#!/usr/bin/env bash

# Script to extract the Singleplayer mission world

# Set the TOMCAT environment variable, assuming that the directory structure
# mirrors that of the git repository.
TOMCAT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd)"
export TOMCAT

pushd "$TOMCAT"/data/worlds > /dev/null
    tar -xzf Singleplayer.tgz
popd > /dev/null
