#!/usr/bin/env python3

# This program takes a UUID as a command-line argument and prints out a JSON
# object to standard output. The object contains the following information:
#   session_id: The UUID of the session
#   timestamp: A timestamp corresponding to the timestamp of the session
#   player_id: A unique ID corresponding to the player.

import os
import sys
import json
import hashlib
from datetime import datetime

# Return UTC date and time in ISO-8601 format.
timestamp = datetime.utcnow().isoformat()[:-3] + "Z"

player_id = sys.argv[2]
player_id_hashed = hashlib.sha256(player_id.encode()).hexdigest()

metadata = {
    "session_id": sys.argv[1],  # Get UUID from command line argument
    "timestamp": timestamp,
    "player_id": player_id_hashed
}

print(json.dumps(metadata, indent=4))  # Serialize metadata
