#!/usr/bin/env python3

# This program takes a UUID as a command-line argument and prints out a JSON
# object to standard output. The object contains the following information:
#   session_id: The UUID of the session
#   timestamp: A timestamp corresponding to the timestamp of the session
#   player_id: A unique ID corresponding to the player.
#   level_of_difficulty: The level of difficulty of the mission (only if
#   MAIN_MISSION=1)
#   spec_version: The version of the spec corresponding to the format of the
#   messages.

import os
import sys
import json
import hashlib
from datetime import datetime

if __name__ == "__main__":
    # Return UTC date and time in ISO-8601 format.
    timestamp = datetime.utcnow().isoformat() + "Z"

    player_id = sys.argv[2]
    player_id_hashed = hashlib.sha256(player_id.encode()).hexdigest()

    metadata = {
        "session_id": sys.argv[1],  # Get UUID from command line argument
        "timestamp": timestamp + "Z",
        "player_id": player_id_hashed,
        "time_limit": sys.argv[3],
        "level_of_difficulty": sys.argv[4],
        "spec_version": sys.argv[5],
    }

    print(json.dumps(metadata, indent=4))  # Serialize metadata
