#!/bin/bash

set -Eeuo pipefail

# Set the TOMCAT environment variable, assuming that the directory structure
# mirrors that of the git repository.
TOMCAT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export TOMCAT

###############################################################################

${TOMCAT}/tools/install_dependencies

if [ "${GITHUB_ACTIONS:-false}" = "true" ]; then
  echo "Running on Github Actions"
fi

pushd "${TOMCAT}"
    echo "Building ToMCAT in `pwd`"

    /bin/rm -rf build
    mkdir build

    # Trying to set the correct version of Java.
    export PATH="$PATH:/opt/local/bin:/opt/local/sbin"
    macports_found=`[ -x "$(command -v port)" ]; echo $?`
    if [[ $macports_found -eq 0 ]]; then
      export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home
    fi
    pushd build > /dev/null 
        if [ "${GITHUB_ACTIONS:-false}" = "true" ]; then
            cmake ${TOMCAT} -DBoost_ARCHITECTURE=-x64\
                            -DBOOST_ROOT=$BOOST_ROOT_1_69_0
        else
            cmake ${TOMCAT}
        fi;

        make -j
        make -j Minecraft

    popd > /dev/null 
popd > /dev/null 

${TOMCAT}/tools/download/tomcat_worlds


if [[ ! -d ${TOMCAT}/data/OpenFace_models ]]; then
  ${TOMCAT}/tools/download/OpenFace_models
fi

echo " "
echo "Finished installing ToMCAT in ${TOMCAT}!"
echo " "
exit 0
