#!/usr/bin/env bash

# Script to install and launch Mumble.

set -eu pipefail

# Set the Mumble version to install.
export MUMBLE_VERSION=1.3.2

if [[ ! "$OSTYPE" == "darwin"* ]]; then
    echo "This script currently only works on macOS. Exiting now."
    exit 1
fi

# Check to see if Mumble is already installed.
if [[ ! -d /Applications/Mumble.app ]]; then
    # Check to see if Mumble-${MUMBLE_VERSION}.dmg exists in the current directory.
    if [[ ! -f Mumble-${MUMBLE_VERSION}.dmg ]]; then
        echo "Downloading Mumble-${MUMBLE_VERSION}.dmg..."
        curl -LO https://dl.mumble.info/stable/Mumble-${MUMBLE_VERSION}.dmg
    fi

    # If the .dmg file exists in the current directory, then mount it using
    # hdiutil.
    if [[ -f Mumble-${MUMBLE_VERSION}.dmg ]]; then
        echo "Mounting the Mumble disk image..."
        hdiutil attach Mumble-${MUMBLE_VERSION}.dmg
    fi

    # Check to see if the disk image is mounted.
    if [[ -d "/Volumes/Mumble ${MUMBLE_VERSION}" ]]; then
        echo "Copying Mumble.app to /Applications..."
        # Copy Mumble.app to the /Applications
        cp -R "/Volumes/Mumble ${MUMBLE_VERSION}/Mumble.app" /Applications

        # Unmount the disk image.
        echo "Unmounting the Mumble disk image..."
        hdiutil unmount "/Volumes/Mumble ${MUMBLE_VERSION}"
    fi

    # Remove the disk image file once the installation is complete
    echo "Finished installing Mumble. Removing Mumble-${MUMBLE_VERSION}.dmg..."
    /bin/rm Mumble-${MUMBLE_VERSION}.dmg

    echo "Mumble installation complete!"
fi


# Launch the Mumble app
echo "Launching Mumble."
open -a Mumble.app

# The line below adds the laplace server. However, it cannot be called before
# Mumble is launched and shutdown at least once, in order to create the SQLite3
# database that holds the configuration settings.
#./tools/add_mumble_server

# Uncomment the line below to hide the Mumble GUI after it's launched.
#osascript -e 'tell application "System Events" to tell process "Mumble" to set visible to false'
exit 0
