#!/usr/bin/env bash

# This is a convenience script for correctly installing the Soartex Fanver
# texture pack for nicer visuals in Minecraft.
# To use this script, first download the texture pack by visiting
# https://www.curseforge.com/minecraft/texture-packs/soartex-fanver-vanilla/download/2371741
# in your web browser and placing the downloaded folder in the tomcat root
# directory, then run this script.

set -u

# Set the TOMCAT environment variable, assuming that the directory structure
# mirrors that of the git repository.
TOMCAT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd)"
export TOMCAT

# Location of the netrc file
NETRC="$TOMCAT"/conf/netrc

pushd "$TOMCAT" > /dev/null
    if [[ ! -f ${NETRC} ]]; then
        echo "${NETRC} not found! We cannot download the Soartex_Fanver "\
             "textures."
        exit 1
    fi

    echo "Downloading the Soartex Fanver textures..."
    echo ""

    curl -O --netrc-file ${NETRC}\
    http://vision.cs.arizona.edu/~tomcat/Soartex_Fanver.tar.gz
    if [[ $? -ne 0 ]]; then exit 1; fi

    echo "Extracting files..."
    if ! tar -xzf Soartex_Fanver.tar.gz; then exit 1; fi

    echo "Resetting folder ${TOMCAT}/external/malmo/Minecraft/run/resourcepacks/tomcat..."
    rm -rf external/malmo/Minecraft/run/resourcepacks/tomcat
    git checkout external/malmo/Minecraft/run/resourcepacks/tomcat

    echo "Copying assets..."
    cp -r Soartex_Fanver/assets\
        external/malmo/Minecraft/run/resourcepacks/tomcat

    # We run 'git checkout' to restore Zombie invasion-specific textures.
    git checkout external/malmo/Minecraft/run/resourcepacks/tomcat

    echo "Removing Soartex_Fanver directory..."
    rm -rf Soartex_Fanver
    echo "Soartex Fanver textures installation successfully completed."

popd > /dev/null

exit 0
