#!/usr/bin/env bash

# Set the TOMCAT environment variable, assuming that the directory structure
# mirrors that of the git repository.
TOMCAT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd)"
export TOMCAT

source "$TOMCAT"/tools/configuration_helpers

configure_session

cd "$TOMCAT"/external/malmo/Minecraft
./launchClient.sh
