openapi: 3.0.0

info:
  title: ToMCAT Data Models and Message Topics
  description: A formal specification of data models and message bus topics associated with ToMCAT.
  version: "0.1"

tags:
- name: Common Events
  description: Events common to all missions.
- name: Observations
  description: Data from physical and virtual sensors that take measurements at regular intervals.
- name: Zombie Invasion Events
  description: Events from the Zombie Invasion mission.
- name: USAR Events
  description: Events from the Urban Search-and-Rescue mission.

paths:
  /observations/state:
    subscribe:
      tags:
      - Observations
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateObservation'

  /observations/events/player_interactions/entity_interactions:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityInteraction'

  /observations/events/player_interactions/villager_saved:
    subscribe:
      tags:
      - Zombie Invasion Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VillagerSaved'

  /observations/events/player_interactions/blocks/door:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoorInteraction'

  /observations/events/player_interactions/blocks/lever:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeverEvent'

  /observations/events/player_interactions/blocks/general:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericBlockInteraction'

  /observations/events/player_interactions/blocks/break:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockBreakEvent'

  /observations/events/player_interactions/item_pickup:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemPickedUpEvent'

  /observations/events/player_interactions/equipment_change:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EquipmentChangeEvent'

  /observations/events/mob_attacked:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MobAttacked'

  /observations/events/entity_death:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityDeath'

  /observations/chat:
    subscribe:
      tags:
      - Common Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'

  /observations/events/dog_barks:
    subscribe:
      tags:
      - USAR Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DogBarkEvent'

  /observations/events/hit_controlled_door_opened:
    subscribe:
      tags:
      - Zombie Invasion Events
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HitControlledDoorOpenedEvent'


components:
  schemas:
    Position:
      description: "Position vector"
      properties:
        x:
          type: integer
          example: 10
        y:
          type: integer
          example: 20
        z:
          type: integer
          example: 30
          
    Velocity:
      description: "Velocity vector"
      properties:
        x:
          type: number
        y:
          type: number
        z:
          type: number

    Event:
      properties:
        timestamp:
          type: string
          format: date-time

    PlayerInteraction:
      allOf:
        - $ref: '#/components/schemas/Event'
      properties:
        player_name:
          $ref: '#/components/schemas/PlayerName'
        item_held:
          $ref: '#/components/schemas/Item'

    EntityInteraction:
      allOf:
      - $ref: '#/components/schemas/PlayerInteraction'
      properties:
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.EntityInteraction
        target_id:
          type: string
          format: uuid
        target_position:
          $ref: '#/components/schemas/Position'
        target_velocity:
          $ref: '#/components/schemas/Velocity'
        target_type:
          $ref: '#/components/schemas/EntityType'
      description: "Entity interaction" 

    MobAttacked:
      allOf:
      - $ref: '#/components/schemas/EntityInteraction'
      properties:
        target_health:
          type: number
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.MobAttacked
      description: "Mob attack event."

    BlockBreakEvent:
      allOf:
      - $ref: '#/components/schemas/PlayerInteraction'
      - $ref: '#/components/schemas/BlockProperties'
      properties:
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.BlockBreakEvent

    BlockProperties:
      properties:
        block_position:
          $ref: '#/components/schemas/Position'
        block_material:
          $ref: '#/components/schemas/BlockMaterial'

    BlockInteraction:
      allOf:
      - $ref: '#/components/schemas/PlayerInteraction'
      - $ref: '#/components/schemas/BlockProperties'
      properties:
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.BlockInteraction
        click_type:
          $ref: '#/components/schemas/ClickType'

    VillagerSaved:
      allOf:
        - $ref: '#/components/schemas/Event'
      properties:
        villager_id:
          type: string
          format: uuid
        villager_pos:
          $ref: '#/components/schemas/Position'

    DoorInteraction:
      allOf:
        - $ref: '#/components/schemas/BlockInteraction'
      properties:
        block_material:
          type: string
          examples:
            - minecraft:wooden_door
        block_type:
          type: string
          enum:
            - net.minecraft.block.BlockDoor
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.DoorInteraction
        was_open:
          type: boolean
      description: "Door event."

    LeverEvent:
      allOf:
      - $ref: '#/components/schemas/BlockInteraction'
      properties:
        block_material:
          type: string
          enum:
            - minecraft:lever
        block_type:
          type: string
          enum:
            - net.minecraft.block.BlockLever
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.LeverFlip
        was_powered:
          type: boolean
      description: "Lever event."


    GenericBlockInteraction:
      allOf:
      - $ref: '#/components/schemas/BlockInteraction'
      properties:
        block_material:
          type: string
          $ref: '#/components/schemas/BlockMaterial'
        block_type:
          $ref: '#/components/schemas/BlockType'
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.BlockInteraction
        was_powered:
          type: boolean
      description: "Generic block interaction event."

    ItemPickedUpEvent:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        item:
          type: string
          example: item.item.potion 
        player_name:
          $ref: '#/components/schemas/PlayerName'
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.ItemPickedUp
      description: "Event corresponding to a player picking up an item"


    ItemStack:
      properties:
        item:
          type: string
          example: item.potion
        count:
          type: integer

    EquipmentChangeEvent:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        from:
          $ref: '#/components/schemas/ItemStack'
        to:
          $ref: '#/components/schemas/ItemStack'
        slot:
          type: string
          example: MAINHAND
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.EquipmentChange
        entity_name:
          type: string
          example: tomcat

    EntityDeath:
      allOf:
        - $ref: '#/components/schemas/Event'
      properties:
        entity_type:
          $ref: '#/components/schemas/EntityType'
        entity_name:
          type: string
          example: Zombie
        entity_id:
          type: string
          format: uuid
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.EntityDeath
      
    DogBarkEvent:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        number_of_barks:
          type: integer
          enum:
            - 1
            - 2
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.DogBarkEvent

    PlayerName:
      type: string
      example: tomcat

    BlockType:
      type: string
      example: net.minecraft.block.BlockAir

    StateObservation:
      properties:
        name:
          $ref: '#/components/schemas/PlayerName'
        header:
          properties:
            timestamp:
              type: string
              format: date-time
            message_type:
              type: string
              enum:
                - observation
            version:
              type: string
              example: "0.2"
        msg:
          properties:
            trial_id:
              type: string
              format: uuid
            timestamp:
              type: string
              format: date-time
            source:
              type: string
              example: human
            sub_type:
              type: string
              enum:
                - state
        data:
          properties:
            x:
              type: number
            y:
              type: number
            z:
              type: number
            motion_x:
              type: number
            motion_y:
              type: number
            motion_z:
              type: number
            pitch:
              type: number
            yaw:
              type: number
            world_time:
              type: integer
            total_time:
              type: integer
            id:
              type: string
              format: uuid
            name:
              $ref: '#/components/schemas/PlayerName'
            life:
              type: number
              example: 20.0

    Chat:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        player_name:
          $ref: '#/components/schemas/PlayerName'
        message:
          type: string
          example: "Hello world!"
        event_type:
          type: string
          enum:
            - edu.arizona.tomcat.Events.Chat

    HitControlledDoorOpenedEvent:
      allOf:
      - $ref: '#/components/schemas/Event'
      properties:
        door_position:
          $ref: '#/components/schemas/Position'

    BlockMaterial:
      type: string
      examples:
        - minecraft:air
        - minecraft:barrier
        - minecraft:clay
        - minecraft:glass
        - minecraft:gold_block
        - minecraft:grass
        - minecraft:stone_button
        - minecraft:wood

    Item:
      type: string
      example: Stone Axe

    EntityType:
      type: string
      examples:
        - net.minecraft.entity.monster.EntitySkeleton
        - net.minecraft.entity.monster.EntityZombie
        - net.minecraft.entity.passive.EntityWolf

    ClickType:
      type: string
      enum:
        - right
        - left
    
    SessionMetadata:
      tags:
      - Metadata
      properties:
        session_id:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
        player_id:
          type: string
          format: uuid
        time_limit: integer
        level_of_difficulty: integer

