# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.232'

    - name: Continuous Integration
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv xvfb
        python3 -m venv tomcat_venv
        source tomcat_venv/bin/activate
        pip install exhale recommonmark sphinx-rtd-theme
        ./tools/install.sh
        xvfb-run --auto-servernum ./tools/run_session.sh

    - name: Build docs
      run: cd build && make docs && cd ..

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs
