# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ linux_testing ]
  pull_request:
    branches: [ linux_testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.232'

    - name: Run a multi-line script
      run: |
        ./tools/install.sh
        sudo apt-get install xvfb
        xvfb-run --auto-servernum ./tools/run_session.sh
