#!/bin/bash

# Script to uninstall BlackHole (https://github.com/ExistentialAudio/BlackHole)
# Usage: ./uninstall

sudo rm -rf /Library/Audio/Plug-Ins/HAL/BlackHole.driver
sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod
