#!/bin/bash

# Script to uninstall BlackHole (https://github.com/ExistentialAudio/BlackHole)
# Usage: ./uninstall_blackhole

blackhole_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

pushd "$blackhole_dir" > /dev/null
  sudo port uninstall
  sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod
popd > /dev/null
